name: CI

on: [pull_request]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        job: [lint, test]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - run: npm ci

      - name: Run ${{ matrix.job }}
        run: npm run ${{ matrix.job }}
