name: CI

on: [pull_request]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        job: [lint, test]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

    - name: Install dependencies
      run: npm ci

      - name: Run ${{ matrix.job }}
        run: npm run ${{ matrix.job }}
