name: Create Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm ci

      - name: Run linter and tests
        run: |
          npm run lint
          npm run test

      - name: Create release branch
        run: |
          git checkout -b releases/${{ github.run_number }}
          git push origin releases/${{ github.run_number }}

      - name: Build Docker image
        run: |
          docker build -t cr.yandex/${{ secrets.YANDEX_REGISTRY_ID }}/app:${{ github.run_number }} .
          docker tag cr.yandex/${{ secrets.YANDEX_REGISTRY_ID }}/app:${{ github.run_number }} cr.yandex/${{ secrets.YANDEX_REGISTRY_ID }}/app:${{ github.run_number }}_latest

      - name: Log in to Yandex Cloud Container Registry
        run: |
          docker login \
            --username oauth \
            --password "${{ secrets.YANDEX_REGISTRY_TOKEN }}" \
            cr.yandex

      - name: Push Docker image
        run: |
          docker push cr.yandex/${{ secrets.YANDEX_REGISTRY_ID }}/app:${{ github.run_number }}
          docker push cr.yandex/${{ secrets.YANDEX_REGISTRY_ID }}/app:${{ github.run_number }}_latest

      - name: Set up Git
        run: |
          git config --global user.email "you@yandex.ru"
          git config --global user.name "Tatiana"

      - name: Create tag for main branch
        run: |
          git tag v${{ github.run_number }} -m "Release version ${{ github.run_number }}"
          git push origin v${{ github.run_number }}

      - name: Determine last tag
        id: last_tag
        run: |
          git fetch --tags
          last_tag=$(git describe --tags --abbrev=0)
          echo "last_tag=${last_tag}" >> $GITHUB_ENV

      - name: Generate release notes
        id: notes
        run: |
          echo "## Релиз ${{ github.run_number }}" > release-notes.md
          echo "" >> release-notes.md
          echo "**Автор:** ${{ github.actor }}" >> release-notes.md
          echo "**Дата:** $(date)" >> release-notes.md
          echo "**Список коммитов:**" >> release-notes.md
          git log ${{ env.last_tag }}..HEAD --oneline >> release-notes.md
          echo "" >> release-notes.md
          echo "**Docker-образ:** [Link to Docker image](cr.yandex/${{ secrets.YANDEX_REGISTRY_ID }}/app:${{ github.run_number }})" >> release-notes.md

      - name: Create GitHub Issue
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "Release ${{ github.run_number }}"
          content-filepath: release-notes.md

      - name: Update CHANGELOG.md
        run: |
          echo "Релиз ${{ github.run_number }}" > changelog-temp.md
          echo "" >> changelog-temp.md
          echo "### Commits" >> changelog-temp.md
          git log ${last_tag}..HEAD --oneline >> changelog-temp.md
          echo "" >> changelog-temp.md
          cat CHANGELOG.md >> changelog-temp.md
          mv changelog-temp.md CHANGELOG.md
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG for release ${{ github.run_number }}"
          git push origin main
