name: Create Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm ci

      - name: Run linter and tests
        run: |
          npm run lint
          npm run test

      - name: Create release branch
        run: |
          git checkout -b releases/${{ github.run_number }}
          git push origin releases/${{ github.run_number }}

      - name: Build Docker image
        run: |
          docker build -t cr.yandex/${{ secrets.YANDEX_REGISTRY_ID }}/app:${{ github.run_number }} .
          docker tag cr.yandex/${{ secrets.YANDEX_REGISTRY_ID }}/app:${{ github.run_number }} cr.yandex/${{ secrets.YANDEX_REGISTRY_ID }}/app:${{ github.run_number }}_latest

      - name: Log in to Yandex Cloud Container Registry
        run: |
          docker login \
            --username oauth \
            --password "${{ secrets.YANDEX_REGISTRY_TOKEN }}" \
            cr.yandex

      - name: Push Docker image
        run: |
          docker push cr.yandex/${{ secrets.YANDEX_REGISTRY_ID }}/app:${{ github.run_number }}
          docker push cr.yandex/${{ secrets.YANDEX_REGISTRY_ID }}/app:${{ github.run_number }}_latest

      - name: Set up Git
        run: |
          git config --global user.email "you@yandex.ru"
          git config --global user.name "Tatiana"

  create_tag:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create tag
        run: |
          git tag ${GITHUB_RUN_NUMBER}
          git push origin ${GITHUB_RUN_NUMBER}

  create_github_issue:
    needs: create_tag
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare issue content
        run: |
          echo "## Release ${{ github.run_number }}" > issue_template.md
          echo "- Date: $(date)" >> issue_template.md
          echo "- Author: ${{ github.actor }}" >> issue_template.md
          echo "- Version: ${{ github.run_number }}" >> issue_template.md
          echo "- Docker Image: cr.yandex/${{ secrets.YANDEX_REGISTRY_ID }}/app:${{ github.run_number }}" >> issue_template.md
          echo "- Commits:" >> issue_template.md
          git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"%h - %s" >> issue_template.md

      - name: Create issue
        run: |
          gh issue create \
            --title "Release ${{ github.run_number }}" \
            --body "$(cat issue_template.md)" \
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update_changelog:
    needs: create_tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update CHANGELOG.md
        run: |
          echo "## Release ${{ github.run_number }}" > temp_changelog.md
          echo "- Date: $(date)" >> temp_changelog.md
          echo "- Version: ${{ github.run_number }}" >> temp_changelog.md
          echo "- Docker Image: cr.yandex/${{ secrets.YANDEX_REGISTRY_ID }}/app:${{ github.run_number }}" >> temp_changelog.md
          echo "- Commits:" >> temp_changelog.md
          git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"%h - %s" >> temp_changelog.md
          cat CHANGELOG.md >> temp_changelog.md
          mv temp_changelog.md CHANGELOG.md
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md for release ${{ github.run_number }}"
          git push origin main
