name: Node.js CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        job: [lint, test]
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run ${{ matrix.job }}
